\version "2.24.0"

tempoLIa = \tempoMarkup "Adagio"
tempoLIb = \tempoMarkup "Allegretto"
tempoLIc = \tempoMarkup "A tempo"

\include "notes/cl1.ly"
\include "notes/cl2.ly"
\include "notes/fag1.ly"
\include "notes/fag2.ly"
\include "notes/cor1.ly"
\include "notes/cor2.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/vla.ly"
\include "notes/S.ly"
\include "notes/org.ly"
