\version "2.24.0"

tempoLIIa = \tempoMarkup "Andante"
tempoLIIb = \tempoMarkup "Adagio"

\include "notes/cl1.ly"
\include "notes/cl2.ly"
\include "notes/fag.ly"
\include "notes/cor1.ly"
\include "notes/cor2.ly"
\include "notes/clno1.ly"
\include "notes/clno2.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/vla.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/b.ly"
\include "notes/org.ly"
